# Generated by Django 6.0.5 on 2026-08-29 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Main Course', 'Main Course'), ('Snacks', 'Snacks'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage'), ('Other', 'Other')], max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('prepared_quantity', models.PositiveIntegerField()),
                ('sold_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('wasted_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='waste_management.fooditem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('surplus_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Donated', 'Donated'), ('Consumed', 'Consumed'), ('Disposed', 'Disposed')], default='Available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_records', to='waste_management.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recipient', models.CharField(max_length=150)),
                ('donation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surplus_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='waste_management.surplusfood')),
            ],
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasted_quantity', models.PositiveIntegerField()),
                ('waste_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('Overproduction', 'Overproduction'), ('Spoilage', 'Spoilage'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_record', to='waste_management.productionrecord')),
            ],
        ),
    ]
